storePassword=umrah-tour-20-08-2025-11-26-keystore-password
keyPassword=umrah-tour-20-08-2025-11-26-keystore-password
keyAlias=umrah-tour-20-08-2025-11-26-keystore-alias
storeFile=release-keystore.jks